# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: '@mikbry'
author: 'Mik Bry 🤖'
email: xxx
description: >- # this means to ignore newlines until "baseurl:"
  Innovative CTO & Founder 🚀 • Rust & Web  Full-Stack Expert 💻 • AI Video & 3D Enthusiast 🤖 • 25+ Y in Tech 🏆 Team Leadership 👥• Pushing Tech Boundaries ✨"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mikbry.com" # the base hostname & protocol for your site, e.g. http://example.com
minima:
  social_links:
    github: mikbry
    twitter: mikbry
    linkedin: mikbry

# Build settings
theme: minima

permalink: /blog/:categories/:title

nav_pages:
  - projects.md
  - blog/index.md
  - about.md

google_analytics: UA-156343413-1

show_excerpts: true

plugins:
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
